### ISSUE TITLE
Add product design guidance

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/docs#3]
- Fonts
- Colors
- Design system

Fold into https://github.com/civichackingagency/project-template

**Comment by lukefretwell** [comment]
Suggestions:

* Fonts: Public Sans: https://public-sans.digital.gov/
* Colors: #000000 + #0050d8
* Design system: https://getbootstrap.com/

**Comment by afomi** [comment]
any thoughts on frameworks?  

* [ ] jekyll
* [ ] plain html
* [ ] rails
* [ ] wordpress
* [ ] other

**Comment by afomi** [comment]
https://github.com/civichackingagency/project-template/pull/1

**Comment by lukefretwell** [comment]
@afomi I'm open to all of those frameworks for the projects if that's what you mean?

**Comment by afomi** [comment]
Ah. To clarify, I was wondering if the project template should be or include any specific framework. 
I've just focused on plain .html for now, for simplicity and broadest coverage, as opposed to focused on a specific framework.

**Comment by lukefretwell** [comment]
@afomi yep, I think that's the best approach.
